[workspace]
authors = ["Your Name <1033478553@qq.com>"]
channels = ["conda-forge"]
name = "codegen-server"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.1,<3.15"
pip = ">=25.3,<26"
django = ">=6.0,<7"
llama-index = ">=0.12.52,<0.13"

[pypi-dependencies]
django-stubs = ">=5.2.8, <6"
requests = "*"
